# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test-Psi4

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  build:
    runs-on: ubuntu-latest

    container: 
      image: psi4/psi4:1.9.1
      options: --user root

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniconda-version: 'latest'
          auto-activate-base: false
          python-version: '3.10' 
          
      - name: Initialize Conda for the shell
        run: |
          # Initialize Conda
          conda init bash
          # Restart the shell to apply changes
          bash 
          
      - name: Create Conda environment and install Psi4
        run: |
          python --version
          conda install psi4 python=3.10 -c conda-forge 
      - name: Verify Psi4 installation
        run: |
          psi4 --version

      - name: Verify Psi4 and Python installation
        run: |
          python -c "import psi4; print(f'Psi4 version: {psi4.__version__}')"

      - name: Set up virtual environment and run tests
        run: |

          python -m pip install -e .
          python -m pip install pyscf pytest
          cd tests
          pytest test_chemistry.py
          pytest test_adapt.py
