# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test-Psi4

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:
  build:
    runs-on: ubuntu-latest

    container: 
      image: psi4/psi4:1.9.1
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python environment
        run: |
          python -m venv venv
          ./venv/bin/pip install --upgrade pip
          ./venv/bin/pip install -r requirements.txt 

      - name: Verify Psi4 and Python installation
        run: |
          python -c "import psi4; print(f'Psi4 version: {psi4.__version__}')"

      - name: Set up virtual environment and run tests
        run: |
          python -m venv venv
          ./venv/bin/pip install -e .
          ./venv/bin/pip install pyscf pytest
          cd tests
          ls
          ./../venv/bin/pytest test_chemistry.py
          ./../venv/bin/pytest test_adapt.py
