# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test-Psi4

on:
  push:
    branches: [ master, devel ]
  pull_request:
    branches: [ master, devel ]

jobs:

  build:

    runs-on: ubuntu-latest
    container: 
     image: psi4/psi4:1.9.1
     options: --user root

    steps:
    - name: Install Python 3.10 on Debian
      run: |
        apt-get update
        apt-get install -y python3.10 python3.10-venv python3.10-dev python3-pip
        ln -sf /usr/bin/python3.10 /usr/bin/python
        ln -sf /usr/bin/pip3 /usr/bin/pip
    
        - name: Verify Python installation
          run: python --version

    - name: Install and test Psi4 interface
      run: |
        python -m pip install --upgrade pip
        python -m pip install -r requirements.txt
        python -m pip install -e .
        python -m pip install pyscf
        python -m pip install 'h5py <= 3.1'
        cd tests
        ls
        pytest test_chemistry.py
        pytest test_adapt.py
        cd ../
